sonar.projectKey=cz.milanoid.fizzbuzz:fizz-buzz
sonar.projectName=fizz-buzz
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=8
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.java.libraries=target/dependency
sonar.java.test.libraries=target/dependency
sonar.junit.reportPaths=target/surefire-reports
