name: Java matrix build
on:
  workflow_dispatch:

jobs:
  build-with-java:
    runs-on: homelab-runners
    strategy:
      matrix:
        java-version: [ 8, 11, 17, 21, 22, 23, 25 ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.1
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'maven'
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Build with Maven
      run: mvn -B -q test

  sonar-scan:
    runs-on: homelab-runners
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.1
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'
    - name: Install Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y maven
    - name: Build with Maven
      run: mvn -B -q test
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://sonar.milanoid.net:9000
    - name: Check Quality Gate
      uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: http://sonar.milanoid.net:9000
