name: Java matrix build
on:
  workflow_dispatch:

jobs:
  build-with-java:
    runs-on: arc-runner-set
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: check java version
      run: java -version
      working-directory: ${{ github.workspace }}
    - run: echo "🎉 This job uses runner scale set runners!"
